[manager]
append_keymap= [
    { on   = "<CR>", run  = "plugin --sync smart-enter", desc = "Enter the child directory, or open the file"},
    { on   = "l", run  = "plugin --sync smart-enter", desc = "Enter the child directory, or open the file"},
]
