[opener]
edit = [
    { run = 'nvim "$@"', block = true, for = "unix" },
    { run = "nvim %*",   block = true, for = "windows" },
]
open = [
    { run = 'setsid xdg-open "$@" 1>/dev/null 2>/dev/null', desc = "Open" },
]
